services:
  postgres_db:
    image: postgres:17.4
    hostname: postgres_db
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: event_key
      POSTGRES_USER: next_user
      POSTGRES_PASSWORD: next_pass
    networks:
      - prisma-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U next_user -d event_key" ]
      interval: 5s
      timeout: 2s
      retries: 20
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      args:
        - NEXT_PUBLIC_APP_NAME=${NEXT_PUBLIC_APP_NAME}
        - NEXT_PUBLIC_APP_DESCRIPTION=${NEXT_PUBLIC_APP_DESCRIPTION}
        - BETTER_AUTH_URL=${BETTER_AUTH_URL}
        - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
        - DATABASE_URL=${DATABASE_URL}
    container_name: app
    environment:
      # Application
      NODE_ENV: "production"
      NEXT_PUBLIC_APP_NAME: "AppName"
      NEXT_PUBLIC_APP_DESCRIPTION: "This is the application description."
      ADVANCE_PASS_CHECK: "true"

      # Better Auth
      BETTER_AUTH_SECRET: "lMD1eol2MrTxIZixGYyjwT0G0DQJ6oLJ"
      BETTER_AUTH_URL: "http://localhost:3000"
      BETTER_AUTH_TRUSTED_ORIGINS: "https://example.com,https://*.example.com"

      # DATABASE
      DATABASE_URL: "postgresql://next_user:next_pass@postgres_db:5432/event_key?schema=public"

      # Email Service
      SMTP_HOST: "mail.example.com"
      SMTP_PORT: 587
      SMTP_USER: "user@example.com"
      SMTP_PASS: "**PASSWORD**"
      SMTP_SECURE: false
      FROM_EMAIL: "user <user@example.com>"

    ports:
      - "3000:3000"
    networks:
      - prisma-network
    restart: unless-stopped
    depends_on:
      postgres_db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://127.0.0.1:3000/api/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  prisma-studio:
    image: chavda2772/prisma-studio:latest
    container_name: property_prisma_studio
    restart: always
    ports:
      - "5555:5555"
    environment:
      DATABASE_URL: "postgresql://next_user:next_pass@postgres_db:5432/event_key?schema=public"
      STUDIO_PORT: 5555
      STUDIO_HOST: "0.0.0.0"
      STUDIO_BROWSER: "none"
      AUTO_INTROSPECT: ${AUTO_INTROSPECT:-true}
    networks:
      - prisma-network
    depends_on:
      postgres_db:
        condition: service_healthy
      app:
        condition: service_healthy

networks:
  prisma-network:
    name: prisma-network

volumes:
  postgres_data:
